import { CommonModule } from '@angular/common';
import { importProvidersFrom } from '@angular/core';
import { RouterModule } from '@angular/router';
import { Meta, StoryObj, applicationConfig } from '@storybook/angular';
import { POLYMORPHEUS_CONTEXT } from '../../cdk/polymorpheus';
import { IProfiler, ITiming } from '../../models';
import {
  miniprofilerAsDialog,
  provideMiniProfilerConfig,
} from '../../providers';
import { MiniProfilerDialogService } from '../../services/dialog.service';
import { MiniProfilerQueryDialogComponent } from './miniprofiler-query-dialog.component';

const fakeProfilerResult: IProfiler = {
  Id: '2b36718d-9196-47fb-be6f-b8fdf0a88b45',
  Name: 'Household/FindUserHousehold',
  Started: new Date('2023-06-16T02:00:24.8685012Z'),
  DurationMilliseconds: 502.36,
  MachineName: '1023c6dfa8bd',
  Root: {
    Id: 'e7cf6cfe-e170-4ebe-bbb0-813b5de9d4ae',
    Name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
    DurationMilliseconds: 502.35,
    StartMilliseconds: 0,
    Children: [
      {
        Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
        Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
        DurationMilliseconds: 501.46,
        StartMilliseconds: 0.83,
        Children: [
          {
            Id: 'a174c446-6ea9-4d5a-aa27-84d368098912',
            Name: 'Resource Filter (Execing): SaveTempDataFilter',
            DurationMilliseconds: 0,
            StartMilliseconds: 1.02,
            DurationWithoutChildrenMilliseconds: 0,
            DurationOfChildrenMilliseconds: 0,
            Parent: {
              Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
              Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
              DurationMilliseconds: 501.46,
              StartMilliseconds: 0.83,
              DurationWithoutChildrenMilliseconds: 501.46,
              DurationOfChildrenMilliseconds: 0,
              Depth: 1,
              HasDuplicateCustomTimings: {},
              HasWarnings: {},
            },
            Depth: 2,
            HasDuplicateCustomTimings: {},
            HasWarnings: {},
            IsTrivial: true,
            CustomTimings: {},
            richTiming: [
              {
                start: 1.02,
                finish: 1.02,
              },
            ],
          },
          {
            Id: '299e8fe9-90ea-4fbd-9f13-fdf65e3f83d5',
            Name: 'Action Filter (Execing): UnsupportedContentTypeFilter',
            DurationMilliseconds: 0,
            StartMilliseconds: 1.1,
            DurationWithoutChildrenMilliseconds: 0,
            DurationOfChildrenMilliseconds: 0,
            Parent: {
              Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
              Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
              DurationMilliseconds: 501.46,
              StartMilliseconds: 0.83,
              DurationWithoutChildrenMilliseconds: 501.46,
              DurationOfChildrenMilliseconds: 0,
              Depth: 1,
              HasDuplicateCustomTimings: {},
              HasWarnings: {},
            },
            Depth: 2,
            HasDuplicateCustomTimings: {},
            HasWarnings: {},
            IsTrivial: true,
            CustomTimings: {},
            richTiming: [
              {
                start: 1.1,
                finish: 1.1,
              },
            ],
          },
          {
            Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
            Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
            DurationMilliseconds: 500.93,
            StartMilliseconds: 1.11,
            CustomTimings: {
              sql: [
                {
                  Id: 'fbeb33ce-4357-44ed-a45b-7192a1d1a298',
                  CommandString: 'Connection OpenAsync()',
                  ExecuteType: 'OpenAsync',
                  StackTraceSnippet:
                    'OpenAsync > Start > MoveNext > OpenInternalAsync > Start > MoveNext > ConnectionOpeningAsync > DispatchEventData > Write',
                  StartMilliseconds: 2.55,
                  DurationMilliseconds: 1.99,
                  Errored: false,
                  Parent: {
                    Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
                    Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
                    DurationMilliseconds: 500.93,
                    StartMilliseconds: 1.11,
                    DurationWithoutChildrenMilliseconds: 500.93,
                    DurationOfChildrenMilliseconds: 0,
                    Depth: 2,
                    HasDuplicateCustomTimings: {},
                    HasWarnings: {},
                    HasCustomTimings: true,
                  },
                  CallType: 'sql',
                  PrevGap: {
                    duration: '2.55',
                    start: 0,
                    finish: 2.55,
                    Reason: {
                      name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
                      duration: 2.55,
                    },
                  },
                },
                {
                  Id: '7c592cfa-b3a2-4f30-ad1d-d6d6be65f92e',
                  CommandString:
                    'DECLARE @__userId_0 nvarchar = N\'d0c51ea1-4bdd-4db3-b840-114f2cb93d12\';\n\nSELECT a."Id", a."AccessFailedCount", a."ConcurrencyStamp", a."Email", a."EmailConfirmed", a."FirstName", a."LastName", a."LockoutEnabled", a."LockoutEnd", a."MeMoneyUserId", a."NormalizedEmail", a."NormalizedUserName", a."PasswordHash", a."PhoneNumber", a."PhoneNumberConfirmed", a."SecurityStamp", a."TwoFactorEnabled", a."UserName"\nFROM "AspNetUsers" AS a\nWHERE a."Id" = @__userId_0\nLIMIT 1;',
                  ExecuteType: 'ExecuteReader (Async)',
                  StackTraceSnippet:
                    'InitializeReaderAsync > Start > MoveNext > ExecuteReaderAsync > Start > MoveNext > CommandReaderExecutingAsync > DispatchEventData > Write',
                  StartMilliseconds: 4.6,
                  DurationMilliseconds: 4.73,
                  Errored: false,
                  Parent: {
                    Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
                    Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
                    DurationMilliseconds: 500.93,
                    StartMilliseconds: 1.11,
                    DurationWithoutChildrenMilliseconds: 500.93,
                    DurationOfChildrenMilliseconds: 0,
                    Depth: 2,
                    HasDuplicateCustomTimings: {},
                    HasWarnings: {},
                    HasCustomTimings: true,
                  },
                  CallType: 'sql',
                  PrevGap: {
                    duration: '0.06',
                    start: 4.54,
                    finish: 4.6,
                    Reason: {
                      name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
                      duration: 0.05999999999999961,
                    },
                  },
                },
                {
                  Id: 'cf56cd39-50a9-495d-82a2-0656aa6f15d5',
                  CommandString: 'Connection CloseAsync()',
                  ExecuteType: 'CloseAsync',
                  StackTraceSnippet:
                    'DisposeAsync > DisposeAsync > Start > MoveNext > CloseAsync > Start > MoveNext > ConnectionClosingAsync > DispatchEventData > Write',
                  StartMilliseconds: 11.65,
                  DurationMilliseconds: 43.07,
                  Errored: false,
                  Parent: {
                    Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
                    Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
                    DurationMilliseconds: 500.93,
                    StartMilliseconds: 1.11,
                    DurationWithoutChildrenMilliseconds: 500.93,
                    DurationOfChildrenMilliseconds: 0,
                    Depth: 2,
                    HasDuplicateCustomTimings: {},
                    HasWarnings: {},
                    HasCustomTimings: true,
                  },
                  CallType: 'sql',
                  PrevGap: {
                    duration: '2.32',
                    start: 9.33,
                    finish: 11.65,
                    Reason: {
                      name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
                      duration: 2.3200000000000003,
                    },
                  },
                },
                {
                  Id: '159c6c28-53cb-41f0-948e-f5aaf34291dd',
                  CommandString: 'Connection OpenAsync()',
                  ExecuteType: 'OpenAsync',
                  StackTraceSnippet:
                    'OpenAsync > Start > MoveNext > OpenInternalAsync > Start > MoveNext > ConnectionOpeningAsync > DispatchEventData > Write',
                  StartMilliseconds: 167.7,
                  DurationMilliseconds: 67.02,
                  Errored: false,
                  Parent: {
                    Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
                    Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
                    DurationMilliseconds: 500.93,
                    StartMilliseconds: 1.11,
                    DurationWithoutChildrenMilliseconds: 500.93,
                    DurationOfChildrenMilliseconds: 0,
                    Depth: 2,
                    HasDuplicateCustomTimings: {},
                    HasWarnings: {},
                    HasCustomTimings: true,
                  },
                  CallType: 'sql',
                  PrevGap: {
                    duration: '112.98',
                    start: 54.72,
                    finish: 167.7,
                    Reason: {
                      name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
                      duration: 112.97999999999999,
                    },
                  },
                },
                {
                  Id: '39abc088-6807-4521-a812-5fbad4dcfcc3',
                  CommandString:
                    'DECLARE @__request_UserId_0 nvarchar = N\'e84057ed-f6c1-4eae-9d35-326c1b123f94\';\n\nSELECT h."Id", h."CreatedBy", h."CreatedDate", h."HouseholdId", h."LastModifiedBy", h."LastModifiedDate", h."UserId"\nFROM household_member AS h\nWHERE h."UserId" = @__request_UserId_0\nLIMIT 1;',
                  ExecuteType: 'ExecuteReader (Async)',
                  StackTraceSnippet:
                    'InitializeReaderAsync > Start > MoveNext > ExecuteReaderAsync > Start > MoveNext > CommandReaderExecutingAsync > DispatchEventData > Write',
                  StartMilliseconds: 234.79,
                  DurationMilliseconds: 133.61,
                  Errored: false,
                  Parent: {
                    Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
                    Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
                    DurationMilliseconds: 500.93,
                    StartMilliseconds: 1.11,
                    DurationWithoutChildrenMilliseconds: 500.93,
                    DurationOfChildrenMilliseconds: 0,
                    Depth: 2,
                    HasDuplicateCustomTimings: {},
                    HasWarnings: {},
                    HasCustomTimings: true,
                  },
                  CallType: 'sql',
                  PrevGap: {
                    duration: '0.07',
                    start: 234.71999999999997,
                    finish: 234.79,
                    Reason: {
                      name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
                      duration: 0.0700000000000216,
                    },
                  },
                },
                {
                  Id: '9c561c69-9ff5-49b1-ba42-dde664248ec8',
                  CommandString: 'Connection CloseAsync()',
                  ExecuteType: 'CloseAsync',
                  StackTraceSnippet:
                    'DisposeAsync > DisposeAsync > Start > MoveNext > CloseAsync > Start > MoveNext > ConnectionClosingAsync > DispatchEventData > Write',
                  StartMilliseconds: 368.74,
                  DurationMilliseconds: 21.16,
                  Errored: false,
                  Parent: {
                    Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
                    Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
                    DurationMilliseconds: 500.93,
                    StartMilliseconds: 1.11,
                    DurationWithoutChildrenMilliseconds: 500.93,
                    DurationOfChildrenMilliseconds: 0,
                    Depth: 2,
                    HasDuplicateCustomTimings: {},
                    HasWarnings: {},
                    HasCustomTimings: true,
                  },
                  CallType: 'sql',
                  PrevGap: {
                    duration: '0.34',
                    start: 368.4,
                    finish: 368.74,
                    Reason: {
                      name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
                      duration: 0.34000000000003183,
                    },
                  },
                },
                {
                  Id: '419a08d0-2dee-4e81-bec4-baf4d06606fa',
                  CommandString: 'Connection OpenAsync()',
                  ExecuteType: 'OpenAsync',
                  StackTraceSnippet:
                    'OpenAsync > Start > MoveNext > OpenInternalAsync > Start > MoveNext > ConnectionOpeningAsync > DispatchEventData > Write',
                  StartMilliseconds: 455.91,
                  DurationMilliseconds: 1.76,
                  Errored: false,
                  Parent: {
                    Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
                    Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
                    DurationMilliseconds: 500.93,
                    StartMilliseconds: 1.11,
                    DurationWithoutChildrenMilliseconds: 500.93,
                    DurationOfChildrenMilliseconds: 0,
                    Depth: 2,
                    HasDuplicateCustomTimings: {},
                    HasWarnings: {},
                    HasCustomTimings: true,
                  },
                  CallType: 'sql',
                  PrevGap: {
                    duration: '66.01',
                    start: 389.90000000000003,
                    finish: 455.91,
                    Reason: {
                      name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
                      duration: 66.00999999999999,
                    },
                  },
                },
                {
                  Id: '3ca85d59-0ccb-4978-a521-951a2d8a82e5',
                  CommandString:
                    'DECLARE @__member_HouseholdId_0 nvarchar = N\'bf9e68ae-cee0-4cc7-9678-5c6bda37d258\';\n\nSELECT h."Id", h."Name"\nFROM household AS h\nWHERE h."Id" = @__member_HouseholdId_0\nLIMIT 1;',
                  ExecuteType: 'ExecuteReader (Async)',
                  StackTraceSnippet:
                    'InitializeReaderAsync > Start > MoveNext > ExecuteReaderAsync > Start > MoveNext > CommandReaderExecutingAsync > DispatchEventData > Write',
                  StartMilliseconds: 457.72,
                  DurationMilliseconds: 43.62,
                  Errored: false,
                  Parent: {
                    Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
                    Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
                    DurationMilliseconds: 500.93,
                    StartMilliseconds: 1.11,
                    DurationWithoutChildrenMilliseconds: 500.93,
                    DurationOfChildrenMilliseconds: 0,
                    Depth: 2,
                    HasDuplicateCustomTimings: {},
                    HasWarnings: {},
                    HasCustomTimings: true,
                  },
                  CallType: 'sql',
                  PrevGap: {
                    duration: '0.05',
                    start: 457.67,
                    finish: 457.72,
                    Reason: {
                      name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
                      duration: 0.05000000000001137,
                    },
                  },
                },
                {
                  Id: '67f6295e-ab19-4c28-8ecd-bcbc02188817',
                  CommandString: 'Connection CloseAsync()',
                  ExecuteType: 'CloseAsync',
                  StackTraceSnippet:
                    'DisposeAsync > DisposeAsync > Start > MoveNext > CloseAsync > Start > MoveNext > ConnectionClosingAsync > DispatchEventData > Write',
                  StartMilliseconds: 501.39,
                  DurationMilliseconds: 0.54,
                  Errored: false,
                  Parent: {
                    Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
                    Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
                    DurationMilliseconds: 500.93,
                    StartMilliseconds: 1.11,
                    DurationWithoutChildrenMilliseconds: 500.93,
                    DurationOfChildrenMilliseconds: 0,
                    Depth: 2,
                    HasDuplicateCustomTimings: {},
                    HasWarnings: {},
                    HasCustomTimings: true,
                  },
                  CallType: 'sql',
                  PrevGap: {
                    duration: '0.05',
                    start: 501.34000000000003,
                    finish: 501.39,
                    Reason: {
                      name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
                      duration: 0.049999999999954525,
                    },
                  },
                  NextGap: {
                    duration: '0.42',
                    start: 501.93,
                    finish: 502.35,
                    Reason: {
                      name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
                      duration: 0.4200000000000159,
                    },
                  },
                },
              ],
            },
            DurationWithoutChildrenMilliseconds: 500.93,
            DurationOfChildrenMilliseconds: 0,
            Parent: {
              Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
              Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
              DurationMilliseconds: 501.46,
              StartMilliseconds: 0.83,
              DurationWithoutChildrenMilliseconds: 501.46,
              DurationOfChildrenMilliseconds: 0,
              Depth: 1,
              HasDuplicateCustomTimings: {},
              HasWarnings: {},
            },
            Depth: 2,
            HasDuplicateCustomTimings: {},
            HasWarnings: {},
            CustomTimingStats: {
              sql: {
                Duration: 317.50000000000006,
                Count: 3,
              },
            },
            HasCustomTimings: true,
            richTiming: [
              {
                start: 1.11,
                finish: 502.04,
              },
            ],
          },
          {
            Id: '017fdd8b-c488-4d92-994a-0990e7c0fa91',
            Name: 'Action Filter (Execed): UnsupportedContentTypeFilter',
            DurationMilliseconds: 0,
            StartMilliseconds: 502.07,
            DurationWithoutChildrenMilliseconds: 0,
            DurationOfChildrenMilliseconds: 0,
            Parent: {
              Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
              Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
              DurationMilliseconds: 501.46,
              StartMilliseconds: 0.83,
              DurationWithoutChildrenMilliseconds: 0.5299999999999727,
              DurationOfChildrenMilliseconds: 500.93,
              Depth: 1,
              HasDuplicateCustomTimings: {},
              HasWarnings: {},
            },
            Depth: 2,
            HasDuplicateCustomTimings: {},
            HasWarnings: {},
            IsTrivial: true,
            CustomTimings: {},
            richTiming: [
              {
                start: 502.07,
                finish: 502.07,
              },
            ],
          },
          {
            Id: '55d9a2d9-7710-468b-a081-7916dd6f6600',
            Name: 'Result Filter (Execing): SaveTempDataFilter',
            DurationMilliseconds: 0,
            StartMilliseconds: 502.08,
            DurationWithoutChildrenMilliseconds: 0,
            DurationOfChildrenMilliseconds: 0,
            Parent: {
              Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
              Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
              DurationMilliseconds: 501.46,
              StartMilliseconds: 0.83,
              DurationWithoutChildrenMilliseconds: 0.5299999999999727,
              DurationOfChildrenMilliseconds: 500.93,
              Depth: 1,
              HasDuplicateCustomTimings: {},
              HasWarnings: {},
            },
            Depth: 2,
            HasDuplicateCustomTimings: {},
            HasWarnings: {},
            IsTrivial: true,
            CustomTimings: {},
            richTiming: [
              {
                start: 502.08,
                finish: 502.08,
              },
            ],
          },
          {
            Id: '774d8e65-16e2-453a-af39-e538579edb54',
            Name: 'Result Filter (Execing): ClientErrorResultFilter',
            DurationMilliseconds: 0,
            StartMilliseconds: 502.09,
            DurationWithoutChildrenMilliseconds: 0,
            DurationOfChildrenMilliseconds: 0,
            Parent: {
              Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
              Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
              DurationMilliseconds: 501.46,
              StartMilliseconds: 0.83,
              DurationWithoutChildrenMilliseconds: 0.5299999999999727,
              DurationOfChildrenMilliseconds: 500.93,
              Depth: 1,
              HasDuplicateCustomTimings: {},
              HasWarnings: {},
            },
            Depth: 2,
            HasDuplicateCustomTimings: {},
            HasWarnings: {},
            IsTrivial: true,
            CustomTimings: {},
            richTiming: [
              {
                start: 502.09,
                finish: 502.09,
              },
            ],
          },
          {
            Id: '39b648fa-bb48-44a1-90fc-d23e6654bb6a',
            Name: 'Object: HouseholdDto',
            DurationMilliseconds: 0.14,
            StartMilliseconds: 502.09,
            DurationWithoutChildrenMilliseconds: 0.14,
            DurationOfChildrenMilliseconds: 0,
            Parent: {
              Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
              Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
              DurationMilliseconds: 501.46,
              StartMilliseconds: 0.83,
              DurationWithoutChildrenMilliseconds: 0.5299999999999727,
              DurationOfChildrenMilliseconds: 500.93,
              Depth: 1,
              HasDuplicateCustomTimings: {},
              HasWarnings: {},
            },
            Depth: 2,
            HasDuplicateCustomTimings: {},
            HasWarnings: {},
            IsTrivial: true,
            CustomTimings: {},
            richTiming: [
              {
                start: 502.09,
                finish: 502.22999999999996,
              },
            ],
          },
          {
            Id: '3fb061d1-5e55-4cb3-a263-a55bcdc2a05a',
            Name: 'Result Filter (Execed): ClientErrorResultFilter',
            DurationMilliseconds: 0,
            StartMilliseconds: 502.24,
            DurationWithoutChildrenMilliseconds: 0,
            DurationOfChildrenMilliseconds: 0,
            Parent: {
              Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
              Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
              DurationMilliseconds: 501.46,
              StartMilliseconds: 0.83,
              DurationWithoutChildrenMilliseconds: 0.3899999999999727,
              DurationOfChildrenMilliseconds: 501.07,
              Depth: 1,
              HasDuplicateCustomTimings: {},
              HasWarnings: {},
            },
            Depth: 2,
            HasDuplicateCustomTimings: {},
            HasWarnings: {},
            IsTrivial: true,
            CustomTimings: {},
            richTiming: [
              {
                start: 502.24,
                finish: 502.24,
              },
            ],
          },
          {
            Id: 'f8e6bfe9-c369-488c-b401-34bc08bc89d0',
            Name: 'Result Filter (Execed): SaveTempDataFilter',
            DurationMilliseconds: 0,
            StartMilliseconds: 502.24,
            DurationWithoutChildrenMilliseconds: 0,
            DurationOfChildrenMilliseconds: 0,
            Parent: {
              Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
              Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
              DurationMilliseconds: 501.46,
              StartMilliseconds: 0.83,
              DurationWithoutChildrenMilliseconds: 0.3899999999999727,
              DurationOfChildrenMilliseconds: 501.07,
              Depth: 1,
              HasDuplicateCustomTimings: {},
              HasWarnings: {},
            },
            Depth: 2,
            HasDuplicateCustomTimings: {},
            HasWarnings: {},
            IsTrivial: true,
            CustomTimings: {},
            richTiming: [
              {
                start: 502.24,
                finish: 502.24,
              },
            ],
          },
          {
            Id: '1063cba2-86ab-4c30-a9b5-f665be090f32',
            Name: 'Resource Filter (Execed): SaveTempDataFilter',
            DurationMilliseconds: 0,
            StartMilliseconds: 502.25,
            DurationWithoutChildrenMilliseconds: 0,
            DurationOfChildrenMilliseconds: 0,
            Parent: {
              Id: 'b4b4c3d3-f09f-4f1b-8afb-c6455a09f2f8',
              Name: 'Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
              DurationMilliseconds: 501.46,
              StartMilliseconds: 0.83,
              DurationWithoutChildrenMilliseconds: 0.3899999999999727,
              DurationOfChildrenMilliseconds: 501.07,
              Depth: 1,
              HasDuplicateCustomTimings: {},
              HasWarnings: {},
            },
            Depth: 2,
            HasDuplicateCustomTimings: {},
            HasWarnings: {},
            IsTrivial: true,
            CustomTimings: {},
            richTiming: [
              {
                start: 502.25,
                finish: 502.25,
              },
            ],
          },
        ],
        DurationWithoutChildrenMilliseconds: 0.3899999999999727,
        DurationOfChildrenMilliseconds: 501.07,
        Parent: {
          Id: 'e7cf6cfe-e170-4ebe-bbb0-813b5de9d4ae',
          Name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          DurationMilliseconds: 502.35,
          StartMilliseconds: 0,
          DurationWithoutChildrenMilliseconds: 502.35,
          DurationOfChildrenMilliseconds: 0,
          Depth: 0,
          HasDuplicateCustomTimings: {},
          HasWarnings: {},
        },
        Depth: 1,
        HasDuplicateCustomTimings: {},
        HasWarnings: {},
        IsTrivial: true,
        CustomTimings: {},
        richTiming: [
          {
            start: 0.83,
            finish: 502.28999999999996,
          },
        ],
      },
    ],
    DurationWithoutChildrenMilliseconds: 0.8900000000000432,
    DurationOfChildrenMilliseconds: 501.46,
    Depth: 0,
    HasDuplicateCustomTimings: {},
    HasWarnings: {},
    IsTrivial: true,
    CustomTimings: {},
    richTiming: [
      {
        start: 0,
        finish: 502.35,
      },
    ],
  },
  User: '127.0.0.1',
  HasUserViewed: true,
  CustomTimingStats: {
    sql: {
      Duration: 317.50000000000006,
      Count: 3,
    },
  },
  CustomLinks: {},
  AllCustomTimings: [
    {
      Id: 'fbeb33ce-4357-44ed-a45b-7192a1d1a298',
      CommandString: 'Connection OpenAsync()',
      ExecuteType: 'OpenAsync',
      StackTraceSnippet:
        'OpenAsync > Start > MoveNext > OpenInternalAsync > Start > MoveNext > ConnectionOpeningAsync > DispatchEventData > Write',
      StartMilliseconds: 2.55,
      DurationMilliseconds: 1.99,
      Errored: false,
      Parent: {
        Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
        Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
        DurationMilliseconds: 500.93,
        StartMilliseconds: 1.11,
        DurationWithoutChildrenMilliseconds: 500.93,
        DurationOfChildrenMilliseconds: 0,
        Depth: 2,
        HasDuplicateCustomTimings: {},
        HasWarnings: {},
        HasCustomTimings: true,
      },
      CallType: 'sql',
      PrevGap: {
        duration: '2.55',
        start: 0,
        finish: 2.55,
        Reason: {
          name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          duration: 2.55,
        },
      },
    },
    {
      Id: '7c592cfa-b3a2-4f30-ad1d-d6d6be65f92e',
      CommandString:
        'DECLARE @__userId_0 nvarchar = N\'d0c51ea1-4bdd-4db3-b840-114f2cb93d12\';\n\nSELECT a."Id", a."AccessFailedCount", a."ConcurrencyStamp", a."Email", a."EmailConfirmed", a."FirstName", a."LastName", a."LockoutEnabled", a."LockoutEnd", a."MeMoneyUserId", a."NormalizedEmail", a."NormalizedUserName", a."PasswordHash", a."PhoneNumber", a."PhoneNumberConfirmed", a."SecurityStamp", a."TwoFactorEnabled", a."UserName"\nFROM "AspNetUsers" AS a\nWHERE a."Id" = @__userId_0\nLIMIT 1;',
      ExecuteType: 'ExecuteReader (Async)',
      StackTraceSnippet:
        'InitializeReaderAsync > Start > MoveNext > ExecuteReaderAsync > Start > MoveNext > CommandReaderExecutingAsync > DispatchEventData > Write',
      StartMilliseconds: 4.6,
      DurationMilliseconds: 4.73,
      Errored: false,
      Parent: {
        Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
        Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
        DurationMilliseconds: 500.93,
        StartMilliseconds: 1.11,
        DurationWithoutChildrenMilliseconds: 500.93,
        DurationOfChildrenMilliseconds: 0,
        Depth: 2,
        HasDuplicateCustomTimings: {},
        HasWarnings: {},
        HasCustomTimings: true,
      },
      CallType: 'sql',
      PrevGap: {
        duration: '0.06',
        start: 4.54,
        finish: 4.6,
        Reason: {
          name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          duration: 0.05999999999999961,
        },
      },
    },
    {
      Id: 'cf56cd39-50a9-495d-82a2-0656aa6f15d5',
      CommandString: 'Connection CloseAsync()',
      ExecuteType: 'CloseAsync',
      StackTraceSnippet:
        'DisposeAsync > DisposeAsync > Start > MoveNext > CloseAsync > Start > MoveNext > ConnectionClosingAsync > DispatchEventData > Write',
      StartMilliseconds: 11.65,
      DurationMilliseconds: 43.07,
      Errored: false,
      Parent: {
        Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
        Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
        DurationMilliseconds: 500.93,
        StartMilliseconds: 1.11,
        DurationWithoutChildrenMilliseconds: 500.93,
        DurationOfChildrenMilliseconds: 0,
        Depth: 2,
        HasDuplicateCustomTimings: {},
        HasWarnings: {},
        HasCustomTimings: true,
      },
      CallType: 'sql',
      PrevGap: {
        duration: '2.32',
        start: 9.33,
        finish: 11.65,
        Reason: {
          name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          duration: 2.3200000000000003,
        },
      },
    },
    {
      Id: '159c6c28-53cb-41f0-948e-f5aaf34291dd',
      CommandString: 'Connection OpenAsync()',
      ExecuteType: 'OpenAsync',
      StackTraceSnippet:
        'OpenAsync > Start > MoveNext > OpenInternalAsync > Start > MoveNext > ConnectionOpeningAsync > DispatchEventData > Write',
      StartMilliseconds: 167.7,
      DurationMilliseconds: 67.02,
      Errored: false,
      Parent: {
        Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
        Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
        DurationMilliseconds: 500.93,
        StartMilliseconds: 1.11,
        DurationWithoutChildrenMilliseconds: 500.93,
        DurationOfChildrenMilliseconds: 0,
        Depth: 2,
        HasDuplicateCustomTimings: {},
        HasWarnings: {},
        HasCustomTimings: true,
      },
      CallType: 'sql',
      PrevGap: {
        duration: '112.98',
        start: 54.72,
        finish: 167.7,
        Reason: {
          name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          duration: 112.97999999999999,
        },
      },
    },
    {
      Id: '39abc088-6807-4521-a812-5fbad4dcfcc3',
      CommandString:
        'DECLARE @__request_UserId_0 nvarchar = N\'e84057ed-f6c1-4eae-9d35-326c1b123f94\';\n\nSELECT h."Id", h."CreatedBy", h."CreatedDate", h."HouseholdId", h."LastModifiedBy", h."LastModifiedDate", h."UserId"\nFROM household_member AS h\nWHERE h."UserId" = @__request_UserId_0\nLIMIT 1;',
      ExecuteType: 'ExecuteReader (Async)',
      StackTraceSnippet:
        'InitializeReaderAsync > Start > MoveNext > ExecuteReaderAsync > Start > MoveNext > CommandReaderExecutingAsync > DispatchEventData > Write',
      StartMilliseconds: 234.79,
      DurationMilliseconds: 133.61,
      Errored: false,
      Parent: {
        Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
        Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
        DurationMilliseconds: 500.93,
        StartMilliseconds: 1.11,
        DurationWithoutChildrenMilliseconds: 500.93,
        DurationOfChildrenMilliseconds: 0,
        Depth: 2,
        HasDuplicateCustomTimings: {},
        HasWarnings: {},
        HasCustomTimings: true,
      },
      CallType: 'sql',
      PrevGap: {
        duration: '0.07',
        start: 234.71999999999997,
        finish: 234.79,
        Reason: {
          name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          duration: 0.0700000000000216,
        },
      },
    },
    {
      Id: '9c561c69-9ff5-49b1-ba42-dde664248ec8',
      CommandString: 'Connection CloseAsync()',
      ExecuteType: 'CloseAsync',
      StackTraceSnippet:
        'DisposeAsync > DisposeAsync > Start > MoveNext > CloseAsync > Start > MoveNext > ConnectionClosingAsync > DispatchEventData > Write',
      StartMilliseconds: 368.74,
      DurationMilliseconds: 21.16,
      Errored: false,
      Parent: {
        Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
        Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
        DurationMilliseconds: 500.93,
        StartMilliseconds: 1.11,
        DurationWithoutChildrenMilliseconds: 500.93,
        DurationOfChildrenMilliseconds: 0,
        Depth: 2,
        HasDuplicateCustomTimings: {},
        HasWarnings: {},
        HasCustomTimings: true,
      },
      CallType: 'sql',
      PrevGap: {
        duration: '0.34',
        start: 368.4,
        finish: 368.74,
        Reason: {
          name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          duration: 0.34000000000003183,
        },
      },
    },
    {
      Id: '419a08d0-2dee-4e81-bec4-baf4d06606fa',
      CommandString: 'Connection OpenAsync()',
      ExecuteType: 'OpenAsync',
      StackTraceSnippet:
        'OpenAsync > Start > MoveNext > OpenInternalAsync > Start > MoveNext > ConnectionOpeningAsync > DispatchEventData > Write',
      StartMilliseconds: 455.91,
      DurationMilliseconds: 1.76,
      Errored: false,
      Parent: {
        Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
        Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
        DurationMilliseconds: 500.93,
        StartMilliseconds: 1.11,
        DurationWithoutChildrenMilliseconds: 500.93,
        DurationOfChildrenMilliseconds: 0,
        Depth: 2,
        HasDuplicateCustomTimings: {},
        HasWarnings: {},
        HasCustomTimings: true,
      },
      CallType: 'sql',
      PrevGap: {
        duration: '66.01',
        start: 389.90000000000003,
        finish: 455.91,
        Reason: {
          name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          duration: 66.00999999999999,
        },
      },
    },
    {
      Id: '3ca85d59-0ccb-4978-a521-951a2d8a82e5',
      CommandString:
        'DECLARE @__member_HouseholdId_0 nvarchar = N\'bf9e68ae-cee0-4cc7-9678-5c6bda37d258\';\n\nSELECT h."Id", h."Name"\nFROM household AS h\nWHERE h."Id" = @__member_HouseholdId_0\nLIMIT 1;',
      ExecuteType: 'ExecuteReader (Async)',
      StackTraceSnippet:
        'InitializeReaderAsync > Start > MoveNext > ExecuteReaderAsync > Start > MoveNext > CommandReaderExecutingAsync > DispatchEventData > Write',
      StartMilliseconds: 457.72,
      DurationMilliseconds: 43.62,
      Errored: false,
      Parent: {
        Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
        Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
        DurationMilliseconds: 500.93,
        StartMilliseconds: 1.11,
        DurationWithoutChildrenMilliseconds: 500.93,
        DurationOfChildrenMilliseconds: 0,
        Depth: 2,
        HasDuplicateCustomTimings: {},
        HasWarnings: {},
        HasCustomTimings: true,
      },
      CallType: 'sql',
      PrevGap: {
        duration: '0.05',
        start: 457.67,
        finish: 457.72,
        Reason: {
          name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          duration: 0.05000000000001137,
        },
      },
    },
    {
      Id: '67f6295e-ab19-4c28-8ecd-bcbc02188817',
      CommandString: 'Connection CloseAsync()',
      ExecuteType: 'CloseAsync',
      StackTraceSnippet:
        'DisposeAsync > DisposeAsync > Start > MoveNext > CloseAsync > Start > MoveNext > ConnectionClosingAsync > DispatchEventData > Write',
      StartMilliseconds: 501.39,
      DurationMilliseconds: 0.54,
      Errored: false,
      Parent: {
        Id: 'cb3488a4-39e6-4f04-9491-3178424a15bf',
        Name: 'Controller Action: MeMoney.WebUI.Controllers.Api.HouseholdController.FindUserHousehold',
        DurationMilliseconds: 500.93,
        StartMilliseconds: 1.11,
        DurationWithoutChildrenMilliseconds: 500.93,
        DurationOfChildrenMilliseconds: 0,
        Depth: 2,
        HasDuplicateCustomTimings: {},
        HasWarnings: {},
        HasCustomTimings: true,
      },
      CallType: 'sql',
      PrevGap: {
        duration: '0.05',
        start: 501.34000000000003,
        finish: 501.39,
        Reason: {
          name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          duration: 0.049999999999954525,
        },
      },
      NextGap: {
        duration: '0.42',
        start: 501.93,
        finish: 502.35,
        Reason: {
          name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
          duration: 0.4200000000000159,
        },
      },
    },
  ],
  HasTrivialTimings: true,
  HasCustomTimings: true,
};

const fakeTiming: ITiming = {
  Id: 'dfc8c705-6b18-43e5-bb0e-cea1dfb410ce',
  Name: 'MiniProfiler Init',
  DurationMilliseconds: 0.58,
  StartMilliseconds: 0.01,
  Children: [],
  DurationWithoutChildrenMilliseconds: 0.58,
  DurationOfChildrenMilliseconds: 0,
  Parent: {
    Id: '81aa3d1d-30e9-4a61-a6fd-8c7c10a23784',
    Name: 'https://localhost:5001/api/household/user/e84057ed-f6c1-4eae-9d35-326c1b123f94',
    DurationMilliseconds: 1436.89,
    StartMilliseconds: 0,
    DurationWithoutChildrenMilliseconds: 1436.89,
    DurationOfChildrenMilliseconds: 0,
    Depth: 0,
    HasDuplicateCustomTimings: {},
    HasWarnings: {},
  },
  Depth: 1,
  HasDuplicateCustomTimings: {},
  HasWarnings: {},
  IsTrivial: true,
  CustomTimings: {},
  richTiming: [
    {
      start: 0.01,
      finish: 0.59,
    },
  ],
};

const meta: Meta = {
  title: 'MiniProfilerQueryDialogComponent',
  component: MiniProfilerQueryDialogComponent,
  decorators: [
    // Define application-wide providers with the applicationConfig decorator
    applicationConfig({
      providers: [
        importProvidersFrom(CommonModule, RouterModule),
        provideMiniProfilerConfig({
          api: 'https://localhost:5001/profiler',
          path: 'https://localhost:5001/profiler',
          queryDialogUI: 'alternative',
        }),
        miniprofilerAsDialog(MiniProfilerDialogService),
        {
          provide: POLYMORPHEUS_CONTEXT,
          useValue: {
            data: {
              profilerResult: fakeProfilerResult,
              timing: fakeTiming,
            },
          },
        },
      ],
    }),
  ],
};

export default meta;

type Story = StoryObj<MiniProfilerQueryDialogComponent>;

export const DefaultUI: Story = {
  render: () => ({
    // Define application-wide providers directly in the render function
    applicationConfig: {
      providers: [
        provideMiniProfilerConfig({
          api: 'https://localhost:5001/profiler',
          path: 'https://localhost:5001/profiler',
          queryDialogUI: 'default',
        }),
      ],
    },
  }),
};

export const AlternativeUI: Story = {
  render: () => ({
    // Define application-wide providers directly in the render function
    applicationConfig: {
      providers: [
        provideMiniProfilerConfig({
          api: 'https://localhost:5001/profiler',
          path: 'https://localhost:5001/profiler',
          queryDialogUI: 'alternative',
        }),
      ],
    },
  }),
};
